# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14vrbQv2ChsE7UZlirgLwZfz6pqTCcEL6
"""

!pip install tpot

import numpy as np 
import pandas as pd 
from sklearn import preprocessing 
from sklearn.metrics import mean_squared_error
from tpot import TPOTRegressor
from sklearn.model_selection import train_test_split 
import xgboost

train =  pd.read_csv('train.csv')
test  =  pd.read_csv('test.csv')

print(train.head())

print(train.columns)

train['Item_Weight'].fillna((train['Item_Weight'].mean()), inplace=True)
test['Item_Weight'].fillna((test['Item_Weight'].mean()), inplace=True)

train['Outlet_Establishment_Year'] = 2013 - train['Outlet_Establishment_Year'] 
test['Outlet_Establishment_Year'] = 2013 - test['Outlet_Establishment_Year']

train['Item_Visibility'] = np.sqrt(train['Item_Visibility'])
test['Item_Visibility'] = np.sqrt(test['Item_Visibility'])

test.drop('Item_Outlet_Sales',axis=1,inplace=True)

target = train['Item_Outlet_Sales']
train.drop('Item_Outlet_Sales',axis=1,inplace=True)

train = train[:100]
target = target[:100]

X_train, X_test, y_train, y_test = train_test_split(train, target,
 train_size=0.75, test_size=0.25)

tpot = TPOTRegressor(generations=2, population_size=50, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_boston_pipeline.py')

